version: "3"
services:
  mongo:
    image: mongo:4.0.8
    container_name: mongo
    restart: always # unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
      MONDODB_LOG_DIR: ${MONDODB_LOG_DIR}
    ports:
      - "27017:27017"
    volumes:
      - mongouniversitydbdata:${MONGODB_DATA_DIR}
  server:
    build: .
    container_name: server
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    links:
      - mongo
volumes:
  mongouniversitydbdata: