name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Jest test
        run: npm install && npm run test
